export const ADD_TODO = 'add_todo'
export const CHECK = 'check'
export const CLEAR_COMPLETED = 'clear_completed'
export const FILTER_ALL = 'filter_all'
export const FILTER_ACTIVE = 'filter_active'
export const DELETE_TODO = 'delete_todo'
export const EDIT_TODO = 'edit_todo'